### PR TITLE
fix cut issue when grep uses colored output.

### PR DESCRIPTION
**Pull request by Moddus**
Hi,
in my grep create colored output because of that the script is not able to locate the correct volume to flash. 

Greets,
Moddus

### CODE REVIEW

**Comment by StefanScherer** [comment]
@Moddus Thanks for the hint. Can you please check your environment variables, especially the `GREP_COLOR`?

```
echo $GREP_COLOR
```

I think we can fix this with only a single line in the script setting this variable to `none`.

**Comment by StefanScherer** [comment]
@Moddus Thanks for the hint. Can you please check your environment variables, especially the `GREP_COLOR`?

```
echo $GREP_COLOR
```

I think we can fix this with only a single line in the script setting this variable to `none`.

**Comment by Moddus** [comment]
Hi,
```
echo $GREP_COLOR
```
prints
```
37;45
```

Greets,
Moddus

**Comment by StefanScherer** [comment]
You probably have an alias for grep or the environment variable GREP_OPTIONS set to `--color=always`. That can be a problem if grep's output is piped to another command. `--color=auto` will emit the control characters for only when the output is directly displayed on the terminal.

But to make `flash` more convenient I'll accept your PR. Thanks!

**Pull request merged**
