### PR TITLE
Fix Markdown errors and add wget install on Mac

### PR DESCRIPTION
**Pull request by fxstein**
Fix markdown errors as identified by atom-linter 
See https://atom.io/packages/linter-markdown
Add wget install for those on a Mac

### CODE REVIEW

**Comment by StefanScherer** [comment]
@fxstein Thanks for your contribution. But how to install it?
Even after a

```bash
apm install linter
apm install linter-markdown
```

opening a markdown file in Atom shows me an error: Error cannot find module 'remark'

**Comment by fxstein** [comment]
Let me check. I started using the linter for all my Python code to make it PEP8 compliant and then added php and markdown.

**Comment by fxstein** [comment]
Here we go:

https://github.com/wooorm/remark

```
npm install remark
```

**Comment by StefanScherer** [comment]
Thanks. Will try. But it seems to me that this Atom plugin should install its dependencies better. Not every Atom user has Node.js installed. 
Can we file an issue there?

**Comment by fxstein** [comment]
Completely agree.

**Comment by StefanScherer** [comment]
Doesn't like all of these linter rules (multiple spaces in lists), but I try to get used to it :-)

**Comment by fxstein** [comment]
My sentiments exactly. But I have learned to realize some of these standards are still better than free flow  - especially amongst teams.

Thanks you for accepting the request.

PS: You guys do amazing work! Cant wait to do a loot of cool things with it!

**Pull request merged**
