### PR TITLE
Ported --bootconf to Mac

### PR DESCRIPTION
**Pull request by StefanScherer**
* Ported `--bootconf` to Mac, thanks to @aetherical for the contribution!
* Fixed a bug that created a `occidentalis.txt-e` file.

### CODE REVIEW

**Comment by aetherical** [comment]
It's interesting that you needed the quotes to not make a 'occidentalis.txt-e'; I will paranoia check the man page on Linux, but it's not doing that on this end.

**Comment by StefanScherer** [comment]
This is an odd implementation of sed on the Mac. The -i option is a little weird. :laughing: 
Linux works fine!

**Comment by ascherer** [comment]
See [this post](http://www.unix.com/emergency-unix-and-linux-support/137864-sed-mac-os-versus-linux.html?s=999e7eb5c2ca3477170520e95b7a1775) for details. :o)

**Comment by StefanScherer** [comment]
@ascherer thanks!

**Pull request merged**
