### PR TITLE
Copy custom file to /boot when flashing

### PR DESCRIPTION
**Pull request by flochtililoch**
Adds the ability to specify a custom file to be copied to the boot partition when flashing. I use this to write some configuration (docker-compose files and bash scripts) used for my custom host initialization.

### CODE REVIEW

**Comment by StefanScherer** [comment]
Looks interesting. Will try it out once I‘m back to a machine with SD card slot.

**Comment by StefanScherer** [comment]
LGTM. Nice idea

**Comment by StefanScherer** [comment]
I have released 2.3.0 with that new feature 🎉

**Comment by flochtililoch** [comment]
One caveat to note with this solution, is that the maximum file size that can be copied over is the size that's available on the /boot partition, which in my testing isn't much (36MB available on a recent flash). While this is plenty enough for simple configuration files, this can become a problem if the goal is to install larger data set.

**Pull request merged**
